version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db
      - ./log:/var/log/mongodb
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: -dfdff*&e123456&