version: '3' #版本需与docker-compose版本一致；docker-compose version命令查询版本号
services:
  #redis容器
  redis:
    #定义主机名
    container_name: myredis
    #使用的镜像；注意这里的版本要与第2步redis版本一致
    image: redis
    #docker 重启后，容器自启动
    restart: always
    #容器的映射端口
    ports:
      - 16379:6379 #注意第二个端口必须是redis.conf中的端口号
    command: redis-server /etc/redis.conf #覆盖容器启动的redis.conf
    #定义挂载点
    volumes:
      - ./data:/data #挂载/docker-compose/redis/data至容器
      - ./conf/redis.conf:/etc/redis.conf #挂载conf至容器   
    # privileged: true  #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
   